spring.application.name=restaurantmangement
server.port=8001
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url= jdbc:mysql://localhost:3306/restaurantdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Immu@28
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
security.jwt.secret-key=513c344489bd5120c94654dd155a26b506918a8591e7309371ecae2d699e0d2c
security.jwt.expiration-time=3600000